# Generated by Django 4.0.5 on 2022-08-07 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_claimName', models.CharField(blank=True, max_length=100, null=True)),
                ('claim_claimDescription', models.TextField()),
                ('claim_claimType', models.TextField(blank=True, null=True)),
                ('claim_sender', models.CharField(max_length=200)),
                ('claim_receiver', models.CharField(max_length=200)),
                ('claim_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
