# Generated by Django 4.0.6 on 2022-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_fieldInternalName', models.CharField(max_length=200, unique=True)),
                ('field_fieldExternalName', models.TextField()),
                ('field_fieldDescription', models.TextField()),
                ('field_fieldDataType', models.CharField(max_length=200)),
                ('field_constraints', models.TextField(blank=True, null=True)),
                ('field_PreProcessors', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
