# Generated by Django 4.0.6 on 2022-07-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_broadcastID', models.PositiveBigIntegerField(unique=True)),
                ('broadcast_broadcastRemark', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='field',
            old_name='field_PreProcessors',
            new_name='field_preProcessors',
        ),
    ]
