# Generated by Django 4.0.6 on 2022-07-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_broadcast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='broadcast_broadcastRemark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
