# Generated by Django 4.0.6 on 2022-08-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('didDocument_ID', models.CharField(max_length=200, unique=True)),
                ('didDocument_firstName', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('didDocument_lastName', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('didDocument_emailID', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('didDocument_phoneNo', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('didDocument_resolvableDocument', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
